language: python
python:
#    - "3.4"  # no longer works for pycryptodome
    - "3.6"
    - "3.7"
    - "3.8"
    - "3.9"
    - "3.10.2"
install:
    - "sudo apt-get install nsca"
    - "pip install -r requirements.txt -r requirements-tests.txt"
script: "nosetests tests"
